import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { isBackendEnabled } from '@/lib/supabase';
import * as letterSvc from '@/lib/services/letterEngine';
import type { LetterTemplate, GeneratedLetter } from '@/lib/services/letterEngine';

export type { LetterTemplate, GeneratedLetter } from '@/lib/services/letterEngine';

interface LetterState {
  templates: LetterTemplate[];
  letters: GeneratedLetter[];
  loadFromDb: (tenantId: string) => Promise<void>;
  addTemplate: (t: Omit<LetterTemplate, 'id'>, tenantId?: string) => void;
  updateTemplate: (id: string, updates: Partial<LetterTemplate>) => void;
  deleteTemplate: (id: string) => void;
  addLetter: (l: Omit<GeneratedLetter, 'id'>, tenantId?: string) => void;
  updateLetter: (id: string, updates: Partial<GeneratedLetter>) => void;
  deleteLetter: (id: string) => void;
}

export const useLetterStore = create<LetterState>()(persist((set) => ({
  templates: [
    // ── VIOLATION NOTICES ──
    { id: 'lt1', name: 'Violation Notice — First Warning', category: 'violation', subject: 'Notice of Violation — {{violation_type}}', body: 'Dear {{owner_name}},\n\nThis letter is to notify you that your unit ({{unit_number}}) is in violation of the association\'s rules and regulations regarding {{violation_type}}.\n\nSpecifically: {{violation_details}}\n\nYou have {{cure_period}} days from the date of this notice to correct the violation. Failure to do so may result in fines of {{fee}} as outlined in the governing documents.\n\nPlease respond or correct the issue by {{due_date}}.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'violation_type', label: 'Violation Type', defaultValue: '' }, { name: 'violation_details', label: 'Violation Details', defaultValue: '' }, { name: 'cure_period', label: 'Cure Period (days)', defaultValue: '30' }, { name: 'fee', label: 'Potential Fine Amount', defaultValue: '$100' }, { name: 'due_date', label: 'Compliance Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    { id: 'lt1b', name: 'Violation Notice — Second Warning', category: 'violation', subject: 'Second Notice of Violation — {{violation_type}}', body: 'Dear {{owner_name}},\n\nThis is your second notice regarding a continuing violation at unit {{unit_number}} concerning {{violation_type}}.\n\nOur records show that a first notice was sent on {{first_notice_date}}. The violation has not been corrected.\n\nPursuant to the governing documents, a fine of {{fee}} will be imposed if the violation is not corrected by {{due_date}}. Continued non-compliance may result in additional fines and/or legal action.\n\nPlease contact the management office immediately to discuss resolution.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'violation_type', label: 'Violation Type', defaultValue: '' }, { name: 'first_notice_date', label: 'First Notice Date', defaultValue: '' }, { name: 'fee', label: 'Fine Amount', defaultValue: '$100' }, { name: 'due_date', label: 'Final Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    { id: 'lt1c', name: 'Fine Imposition Notice', category: 'violation', subject: 'Notice of Fine — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nDespite previous notices dated {{previous_notice_dates}}, the violation at unit {{unit_number}} regarding {{violation_type}} has not been corrected.\n\nPursuant to the association\'s governing documents, a fine of {{fee}} has been imposed on your account effective {{effective_date}}. This amount is due by {{due_date}}.\n\nYou have the right to request a hearing before the Board within 14 days of this notice. To request a hearing, please submit a written request to the management office.\n\nIf the violation continues, additional fines of {{recurring_fee}} per {{fine_interval}} will be assessed.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'violation_type', label: 'Violation Type', defaultValue: '' }, { name: 'previous_notice_dates', label: 'Previous Notice Dates', defaultValue: '' }, { name: 'fee', label: 'Fine Amount', defaultValue: '$100' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'due_date', label: 'Payment Due Date', defaultValue: '' }, { name: 'recurring_fee', label: 'Recurring Fine', defaultValue: '$50' }, { name: 'fine_interval', label: 'Fine Interval', defaultValue: 'month' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    { id: 'lt1d', name: 'Hearing Notice — Violation', category: 'violation', subject: 'Notice of Hearing — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nYou are hereby notified that a hearing has been scheduled regarding the violation(s) at unit {{unit_number}}.\n\nHearing Details:\n- Date: {{due_date}}\n- Time: {{hearing_time}}\n- Location: {{hearing_location}}\n- Subject: {{violation_type}}\n\nYou have the right to attend, present evidence, and be heard. You may also submit a written statement in lieu of attending.\n\nIf the Board determines the violation exists, fines of up to {{fee}} may be imposed.\n\nPlease confirm your attendance by contacting the management office.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'violation_type', label: 'Violation Type', defaultValue: '' }, { name: 'due_date', label: 'Hearing Date', defaultValue: '' }, { name: 'hearing_time', label: 'Hearing Time', defaultValue: '7:00 PM' }, { name: 'hearing_location', label: 'Location', defaultValue: 'Community Room' }, { name: 'fee', label: 'Maximum Fine', defaultValue: '$500' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    // ── COLLECTION NOTICES ──
    { id: 'lt2', name: 'Collection — Past Due Notice', category: 'collection', subject: 'Past Due Assessment Notice — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nOur records indicate that your unit ({{unit_number}}) has an outstanding balance of {{fee}}. This amount was due on {{due_date}}.\n\nPer the association\'s collection policy, late fees of {{late_fee}} per month will be assessed on unpaid balances. Please remit payment within {{days_to_pay}} days to avoid further action.\n\nPayment can be made via the resident portal or by check to the management office.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fee', label: 'Amount Due', defaultValue: '' }, { name: 'due_date', label: 'Original Due Date', defaultValue: '' }, { name: 'late_fee', label: 'Late Fee', defaultValue: '$25' }, { name: 'days_to_pay', label: 'Days to Pay', defaultValue: '15' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt2b', name: 'Collection — Intent to Lien', category: 'collection', subject: 'Notice of Intent to File Lien — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nDespite previous notices, your account for unit {{unit_number}} remains delinquent in the amount of {{fee}}, which includes assessments, late fees, and interest through {{through_date}}.\n\nUnless full payment is received by {{due_date}}, the association intends to file a lien against your property pursuant to the governing documents and applicable law.\n\nOnce a lien is filed, you will also be responsible for all recording fees, legal costs, and attorney\'s fees incurred in the collection process.\n\nTo arrange payment or discuss a payment plan, please contact the management office immediately.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fee', label: 'Total Amount Owed', defaultValue: '' }, { name: 'through_date', label: 'Balance Through Date', defaultValue: '' }, { name: 'due_date', label: 'Payment Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt2c', name: 'Collection — Payment Plan Offer', category: 'collection', subject: 'Payment Plan Agreement — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nIn response to your request, the Board has approved a payment plan for the outstanding balance on unit {{unit_number}}.\n\nTotal amount owed: {{fee}}\nPayment plan terms:\n- Monthly payment: {{monthly_payment}}\n- Number of payments: {{num_payments}}\n- First payment due: {{due_date}}\n- Payments due on the 1st of each month thereafter\n\nThis plan is in addition to your regular monthly assessment of {{regular_assessment}}. All current assessments must remain current during the plan period.\n\nIf any payment is missed or more than 10 days late, the full remaining balance becomes immediately due.\n\nPlease sign and return a copy of this letter to the management office by {{due_date}} to confirm acceptance.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fee', label: 'Total Amount Owed', defaultValue: '' }, { name: 'monthly_payment', label: 'Monthly Payment', defaultValue: '' }, { name: 'num_payments', label: 'Number of Payments', defaultValue: '6' }, { name: 'due_date', label: 'First Payment Due', defaultValue: '' }, { name: 'regular_assessment', label: 'Regular Monthly Assessment', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    // ── ASSESSMENT & FINANCIAL NOTICES ──
    { id: 'lt5', name: 'Annual Assessment Notice', category: 'notice', subject: 'Annual Assessment Notice — {{fiscal_year}}', body: 'Dear {{owner_name}},\n\nThe Board of Directors has approved the annual budget for {{fiscal_year}}. Your monthly assessment for unit {{unit_number}} is {{fee}}, effective {{effective_date}}.\n\nAssessments are due on the 1st of each month. Late payments will incur a fee of {{late_fee}} after the {{grace_period}}-day grace period.\n\nKey budget highlights:\n{{budget_highlights}}\n\nThe full budget is available for review at the management office or on the resident portal. If you have questions, please contact the Treasurer.\n\nPayment due date for first new assessment: {{due_date}}\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fiscal_year', label: 'Fiscal Year', defaultValue: '2026' }, { name: 'fee', label: 'Monthly Assessment', defaultValue: '' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'late_fee', label: 'Late Fee', defaultValue: '$25' }, { name: 'grace_period', label: 'Grace Period (days)', defaultValue: '15' }, { name: 'budget_highlights', label: 'Budget Highlights', defaultValue: '' }, { name: 'due_date', label: 'First New Payment Due', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt6', name: 'Special Assessment Notice', category: 'notice', subject: 'Notice of Special Assessment', body: 'Dear {{owner_name}},\n\nAt the {{meeting_type}} meeting held on {{meeting_date}}, the Board of Directors approved a special assessment for {{purpose}}.\n\nYour share for unit {{unit_number}}: {{fee}}\nDue date: {{due_date}}\nPayment options: {{payment_options}}\n\nReason for the special assessment:\n{{reason_details}}\n\nThe total project cost is {{total_cost}}, allocated based on {{allocation_method}}.\n\nIf you have questions or need to discuss payment arrangements, please contact the management office.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fee', label: 'Your Assessment Amount', defaultValue: '' }, { name: 'due_date', label: 'Due Date', defaultValue: '' }, { name: 'purpose', label: 'Purpose', defaultValue: '' }, { name: 'meeting_type', label: 'Meeting Type', defaultValue: 'Board' }, { name: 'meeting_date', label: 'Meeting Date', defaultValue: '' }, { name: 'payment_options', label: 'Payment Options', defaultValue: 'Lump sum or 3 monthly installments' }, { name: 'reason_details', label: 'Detailed Reason', defaultValue: '' }, { name: 'total_cost', label: 'Total Project Cost', defaultValue: '' }, { name: 'allocation_method', label: 'Allocation Method', defaultValue: 'percentage of ownership interest' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt7', name: 'Assessment Increase Notice', category: 'notice', subject: 'Notice of Assessment Increase — Effective {{effective_date}}', body: 'Dear {{owner_name}},\n\nPursuant to the approved {{fiscal_year}} budget, this letter serves as notice that your monthly assessment for unit {{unit_number}} will increase from {{current_fee}} to {{fee}}, effective {{effective_date}}.\n\nThe increase of {{increase_amount}} ({{increase_percent}}%) reflects rising costs in the following areas:\n{{increase_reasons}}\n\nThe first payment at the new rate is due {{due_date}}. If you are enrolled in automatic payments, your payment will be updated automatically.\n\nThe approved budget is available for review on the resident portal.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'fiscal_year', label: 'Fiscal Year', defaultValue: '2026' }, { name: 'current_fee', label: 'Current Monthly Fee', defaultValue: '' }, { name: 'fee', label: 'New Monthly Fee', defaultValue: '' }, { name: 'increase_amount', label: 'Increase Amount', defaultValue: '' }, { name: 'increase_percent', label: 'Increase Percentage', defaultValue: '' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'due_date', label: 'First New Payment Due', defaultValue: '' }, { name: 'increase_reasons', label: 'Reasons for Increase', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    // ── MEETING NOTICES ──
    { id: 'lt8', name: 'Annual Meeting Notice', category: 'notice', subject: 'Notice of Annual Meeting — {{meeting_date}}', body: 'Dear {{owner_name}},\n\nYou are hereby notified that the Annual Meeting of the {{building_name}} will be held as follows:\n\nDate: {{meeting_date}}\nTime: {{meeting_time}}\nLocation: {{meeting_location}}\n\nAgenda:\n1. Call to order and verification of quorum\n2. Approval of prior meeting minutes\n3. Board of Directors election\n4. Presentation of {{fiscal_year}} budget (assessment: {{fee}}/month)\n5. Committee reports\n6. Old business\n7. New business\n8. Owner forum\n9. Adjournment\n\nProxy forms are enclosed for owners unable to attend. Proxies must be received by {{due_date}}.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'meeting_date', label: 'Meeting Date', defaultValue: '' }, { name: 'meeting_time', label: 'Meeting Time', defaultValue: '7:00 PM' }, { name: 'meeting_location', label: 'Location', defaultValue: 'Community Room' }, { name: 'fiscal_year', label: 'Budget Year', defaultValue: '2026' }, { name: 'fee', label: 'Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'Proxy Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Secretary' }] },

    { id: 'lt9', name: 'Special Meeting Notice', category: 'notice', subject: 'Notice of Special Meeting — {{meeting_date}}', body: 'Dear {{owner_name}},\n\nA Special Meeting of the {{building_name}} has been called and will be held as follows:\n\nDate: {{meeting_date}}\nTime: {{meeting_time}}\nLocation: {{meeting_location}}\n\nPurpose: {{meeting_purpose}}\n\nThis meeting requires owner vote. The estimated financial impact is {{fee}} per unit.\n\nProxy forms are enclosed for owners unable to attend. Proxies must be received by {{due_date}}.\n\nYour participation is important — a quorum is required to conduct business.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'meeting_date', label: 'Meeting Date', defaultValue: '' }, { name: 'meeting_time', label: 'Meeting Time', defaultValue: '7:00 PM' }, { name: 'meeting_location', label: 'Location', defaultValue: 'Community Room' }, { name: 'meeting_purpose', label: 'Purpose', defaultValue: '' }, { name: 'fee', label: 'Estimated Cost Per Unit', defaultValue: '' }, { name: 'due_date', label: 'Proxy Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Secretary' }] },

    { id: 'lt10', name: 'Board Meeting Notice', category: 'notice', subject: 'Notice of Board Meeting — {{meeting_date}}', body: 'Dear {{owner_name}},\n\nThe next regular meeting of the Board of Directors of {{building_name}} will be held:\n\nDate: {{meeting_date}}\nTime: {{meeting_time}}\nLocation: {{meeting_location}}\n\nOwners are welcome to attend. An owner forum period will be provided for comments and questions.\n\nAgenda items include review of financials (current assessment: {{fee}}/month), maintenance updates, and any new business.\n\nIf you have items you would like the Board to consider, please submit them in writing to the management office by {{due_date}}.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'meeting_date', label: 'Meeting Date', defaultValue: '' }, { name: 'meeting_time', label: 'Meeting Time', defaultValue: '7:00 PM' }, { name: 'meeting_location', label: 'Location', defaultValue: 'Community Room' }, { name: 'fee', label: 'Current Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'Agenda Submission Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Secretary' }] },

    // ── ELECTION NOTICES ──
    { id: 'lt11', name: 'Election — Call for Candidates', category: 'notice', subject: 'Call for Board Candidates — {{election_year}} Election', body: 'Dear {{owner_name}},\n\nThe Board of Directors of {{building_name}} is seeking candidates for {{num_seats}} open board seat(s) for the {{election_year}} term.\n\nEligibility: All owners in good standing (current on assessments of {{fee}}/month) are eligible to serve.\n\nTo submit your candidacy:\n- Complete the enclosed candidate form\n- Submit a brief biography (250 words or less)\n- Return to the management office by {{due_date}}\n\nThe election will be held at the Annual Meeting on {{election_date}}. Board service is a volunteer position with a term of {{term_length}}.\n\nWe encourage all interested owners to consider serving their community.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'election_year', label: 'Election Year', defaultValue: '2026' }, { name: 'num_seats', label: 'Open Seats', defaultValue: '2' }, { name: 'fee', label: 'Current Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'Candidacy Deadline', defaultValue: '' }, { name: 'election_date', label: 'Election Date', defaultValue: '' }, { name: 'term_length', label: 'Term Length', defaultValue: '2 years' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Secretary' }] },

    { id: 'lt12', name: 'Proxy / Ballot — Election', category: 'notice', subject: 'Official Ballot & Proxy Form — {{election_year}} Board Election', body: 'Dear {{owner_name}},\n\nEnclosed is your official ballot for the {{election_year}} Board of Directors election for {{building_name}}.\n\nUnit: {{unit_number}}\nVoting weight: {{voting_weight}}\nAssessment status: {{fee}} (must be current to vote)\n\nCandidates for {{num_seats}} open seat(s):\n{{candidate_list}}\n\nVoting instructions:\n1. Mark your selections on the enclosed ballot\n2. Place ballot in the inner sealed envelope\n3. Sign the outer envelope\n4. Return by {{due_date}} via mail or in person to the management office\n\nIf you cannot attend the Annual Meeting, you may designate a proxy using the enclosed proxy form.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'election_year', label: 'Election Year', defaultValue: '2026' }, { name: 'num_seats', label: 'Open Seats', defaultValue: '2' }, { name: 'fee', label: 'Current Assessment', defaultValue: '' }, { name: 'voting_weight', label: 'Voting Weight', defaultValue: '1 vote' }, { name: 'candidate_list', label: 'Candidate List', defaultValue: '' }, { name: 'due_date', label: 'Ballot Return Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Secretary' }] },

    // ── INSURANCE & COMPLIANCE ──
    { id: 'lt13', name: 'Insurance Certificate Request', category: 'general', subject: 'Certificate of Insurance Required — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nAs part of the association\'s insurance compliance requirements, we need a current certificate of insurance for your unit ({{unit_number}}).\n\nRequired coverage:\n- HO-6 / unit owner policy\n- Minimum liability: {{min_liability}}\n- Loss assessment coverage recommended: {{fee}}\n- Association named as additional interested party\n\nPlease have your insurance agent send the certificate to the management office by {{due_date}}.\n\nIf your policy has recently renewed, please ensure an updated certificate is on file.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'min_liability', label: 'Minimum Liability', defaultValue: '$300,000' }, { name: 'fee', label: 'Recommended Loss Assessment Coverage', defaultValue: '$50,000' }, { name: 'due_date', label: 'Certificate Deadline', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    // ── ARCHITECTURAL / MODIFICATION ──
    { id: 'lt14', name: 'Architectural Review — Approval', category: 'general', subject: 'Modification Request Approved — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nThe Architectural Review Committee has reviewed your modification request for unit {{unit_number}} dated {{request_date}}.\n\nProject: {{project_description}}\nStatus: APPROVED\nApproval Date: {{approval_date}}\n\nConditions of approval:\n{{conditions}}\n\nPermit/deposit requirements:\n- Refundable deposit: {{fee}} (due by {{due_date}})\n- All work must be completed within {{completion_period}}\n- Contractor must provide certificate of insurance\n- Work hours: {{work_hours}}\n\nPlease schedule a pre-work inspection with the management office before beginning.\n\nSincerely,\n{{sender_name}}\nArchitectural Review Committee', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'request_date', label: 'Request Date', defaultValue: '' }, { name: 'project_description', label: 'Project Description', defaultValue: '' }, { name: 'approval_date', label: 'Approval Date', defaultValue: '' }, { name: 'conditions', label: 'Conditions', defaultValue: '- Work must comply with all building codes\n- No structural modifications' }, { name: 'fee', label: 'Refundable Deposit', defaultValue: '$500' }, { name: 'due_date', label: 'Deposit Due Date', defaultValue: '' }, { name: 'completion_period', label: 'Completion Period', defaultValue: '90 days' }, { name: 'work_hours', label: 'Permitted Work Hours', defaultValue: 'Mon-Fri 9AM-5PM' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt14b', name: 'Architectural Review — Denial', category: 'general', subject: 'Modification Request Denied — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nThe Architectural Review Committee has reviewed your modification request for unit {{unit_number}} dated {{request_date}}.\n\nProject: {{project_description}}\nStatus: DENIED\n\nReason(s) for denial:\n{{denial_reasons}}\n\nYou may resubmit a modified request addressing the concerns noted above. There is no additional fee for resubmission.\n\nIf you wish to appeal this decision, you may do so in writing to the Board of Directors within {{appeal_period}} days. The Board meets on {{due_date}}.\n\nSincerely,\n{{sender_name}}\nArchitectural Review Committee', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'request_date', label: 'Request Date', defaultValue: '' }, { name: 'project_description', label: 'Project Description', defaultValue: '' }, { name: 'denial_reasons', label: 'Reasons for Denial', defaultValue: '' }, { name: 'fee', label: 'Original Application Fee', defaultValue: '$0' }, { name: 'appeal_period', label: 'Appeal Period (days)', defaultValue: '30' }, { name: 'due_date', label: 'Next Board Meeting', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    // ── WELCOME & MOVE-IN/OUT ──
    { id: 'lt3', name: 'Welcome Letter — New Owner', category: 'welcome', subject: 'Welcome to {{building_name}}!', body: 'Dear {{owner_name}},\n\nOn behalf of the Board of Directors, welcome to {{building_name}}! We are pleased to have you as a member of our community.\n\nHere is some important information:\n\n- Monthly assessment: {{fee}} due on the 1st of each month\n- First assessment due: {{due_date}}\n- Resident portal: Access at {{portal_url}}\n- Emergency maintenance line: {{emergency_phone}}\n- Move-in coordinator: Contact the management office to schedule\n\nPlease review the attached house rules and resident handbook. If you have any questions, don\'t hesitate to reach out.\n\nWelcome home!\n\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'fee', label: 'Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'First Assessment Due', defaultValue: '' }, { name: 'portal_url', label: 'Portal URL', defaultValue: '' }, { name: 'emergency_phone', label: 'Emergency Phone', defaultValue: '202-555-9111' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    { id: 'lt15', name: 'Move-In / Move-Out Instructions', category: 'general', subject: 'Move-In/Move-Out Instructions — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nThank you for notifying the association about your upcoming move at unit {{unit_number}}.\n\nMove date: {{move_date}}\nMove-in/out deposit: {{fee}} (refundable)\nDeposit due by: {{due_date}}\n\nRequired steps:\n1. Reserve the elevator: Contact management at least 7 days in advance\n2. Pay the refundable move deposit of {{fee}}\n3. Provide proof of insurance from your moving company\n4. Moving hours: {{move_hours}}\n5. Use designated entrance: {{designated_entrance}}\n6. Protect all common area floors and walls during move\n\nThe deposit will be refunded within 14 days after inspection confirms no damage to common areas.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'move_date', label: 'Move Date', defaultValue: '' }, { name: 'fee', label: 'Move Deposit', defaultValue: '$250' }, { name: 'due_date', label: 'Deposit Due Date', defaultValue: '' }, { name: 'move_hours', label: 'Permitted Move Hours', defaultValue: 'Mon-Fri 9AM-5PM, Sat 10AM-4PM' }, { name: 'designated_entrance', label: 'Designated Entrance', defaultValue: 'Service entrance / loading dock' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Property Manager' }] },

    { id: 'lt16', name: 'Resale / Estoppel Certificate', category: 'general', subject: 'Resale Certificate — Unit {{unit_number}}', body: 'Dear {{owner_name}},\n\nPer your request, the following resale/estoppel information is provided for unit {{unit_number}} as of {{effective_date}}:\n\nAssessment Information:\n- Monthly assessment: {{fee}}\n- Assessment due date: 1st of each month\n- Next due date: {{due_date}}\n- Outstanding balance: {{outstanding_balance}}\n- Special assessments pending: {{special_assessments}}\n\nAssociation Information:\n- Reserve fund balance: {{reserve_balance}}\n- Pending litigation: {{pending_litigation}}\n- Planned capital improvements: {{capital_improvements}}\n\nThis certificate is valid for 30 days from the date of issuance. Processing fee: {{processing_fee}}.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'unit_number', label: 'Unit Number', defaultValue: '' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'fee', label: 'Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'Next Assessment Due', defaultValue: '' }, { name: 'outstanding_balance', label: 'Outstanding Balance', defaultValue: '$0.00' }, { name: 'special_assessments', label: 'Special Assessments Pending', defaultValue: 'None' }, { name: 'reserve_balance', label: 'Reserve Fund Balance', defaultValue: '' }, { name: 'pending_litigation', label: 'Pending Litigation', defaultValue: 'None' }, { name: 'capital_improvements', label: 'Capital Improvements', defaultValue: 'None planned' }, { name: 'processing_fee', label: 'Processing Fee', defaultValue: '$100' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    // ── MAINTENANCE NOTICES ──
    { id: 'lt4', name: 'Maintenance Notice — Scheduled Work', category: 'maintenance', subject: 'Scheduled Maintenance — {{work_type}}', body: 'Dear {{owner_name}},\n\nPlease be advised that {{work_type}} has been scheduled for {{work_date}}.\n\nDetails:\n- Scope: {{work_scope}}\n- Duration: {{duration}}\n- Areas affected: {{affected_areas}}\n- Contractor: {{contractor_name}}\n- Estimated cost: {{fee}} (included in regular assessments)\n\nAction required by: {{due_date}}\n{{additional_notes}}\n\nWe apologize for any inconvenience. Please contact the management office with questions.\n\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: 'Residents' }, { name: 'work_type', label: 'Work Type', defaultValue: '' }, { name: 'work_date', label: 'Work Date', defaultValue: '' }, { name: 'work_scope', label: 'Scope', defaultValue: '' }, { name: 'duration', label: 'Duration', defaultValue: '' }, { name: 'affected_areas', label: 'Affected Areas', defaultValue: '' }, { name: 'contractor_name', label: 'Contractor', defaultValue: '' }, { name: 'fee', label: 'Estimated Cost', defaultValue: '' }, { name: 'due_date', label: 'Action Required By', defaultValue: '' }, { name: 'additional_notes', label: 'Additional Notes', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Vice President' }] },

    { id: 'lt17', name: 'Emergency Maintenance Alert', category: 'maintenance', subject: 'URGENT: Emergency Maintenance — {{work_type}}', body: 'Dear {{owner_name}},\n\nThis is an urgent notice regarding emergency maintenance at {{building_name}}.\n\nIssue: {{work_type}}\nDiscovered: {{discovered_date}}\nAreas affected: {{affected_areas}}\n\nImmediate actions:\n{{immediate_actions}}\n\nEstimated repair cost: {{fee}}\nExpected completion: {{due_date}}\nContractor: {{contractor_name}}\n\nIf you experience any related issues in your unit, please contact the emergency line immediately at {{emergency_phone}}.\n\nWe will provide updates as the situation develops.\n\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: 'Residents' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'work_type', label: 'Emergency Type', defaultValue: '' }, { name: 'discovered_date', label: 'Date Discovered', defaultValue: '' }, { name: 'affected_areas', label: 'Areas Affected', defaultValue: '' }, { name: 'immediate_actions', label: 'Immediate Actions Required', defaultValue: '' }, { name: 'fee', label: 'Estimated Repair Cost', defaultValue: '' }, { name: 'due_date', label: 'Expected Completion', defaultValue: '' }, { name: 'contractor_name', label: 'Contractor', defaultValue: '' }, { name: 'emergency_phone', label: 'Emergency Phone', defaultValue: '202-555-9111' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    // ── GOVERNANCE & POLICY ──
    { id: 'lt18', name: 'Policy Change Notice', category: 'notice', subject: 'Notice of Policy Change — {{policy_name}}', body: 'Dear {{owner_name}},\n\nThe Board of Directors has approved changes to the association\'s {{policy_name}}, effective {{effective_date}}.\n\nKey changes:\n{{change_summary}}\n\nFinancial impact: {{fee}} (if applicable)\nCompliance required by: {{due_date}}\n\nA copy of the updated policy is available on the resident portal and at the management office.\n\nIf you have questions or concerns, please submit them in writing to the Board or attend the next Board meeting on {{next_meeting_date}}.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'policy_name', label: 'Policy Name', defaultValue: '' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'change_summary', label: 'Summary of Changes', defaultValue: '' }, { name: 'fee', label: 'Financial Impact', defaultValue: 'N/A' }, { name: 'due_date', label: 'Compliance Date', defaultValue: '' }, { name: 'next_meeting_date', label: 'Next Board Meeting', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },

    { id: 'lt19', name: 'Annual Disclosure / Financial Statement', category: 'notice', subject: '{{fiscal_year}} Annual Financial Disclosure', body: 'Dear {{owner_name}},\n\nPursuant to the governing documents and applicable law, enclosed is the annual financial disclosure for {{building_name}} for fiscal year {{fiscal_year}}.\n\nFinancial Summary:\n- Total revenue: {{total_revenue}}\n- Total expenses: {{total_expenses}}\n- Reserve fund balance: {{reserve_balance}}\n- Current monthly assessment: {{fee}}\n- Next assessment due: {{due_date}}\n\nKey items:\n{{financial_highlights}}\n\nThe complete audited financial statements are available for inspection at the management office during business hours. Owners may request a copy by contacting the management office.\n\nSincerely,\n{{sender_name}}\nTreasurer', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'fiscal_year', label: 'Fiscal Year', defaultValue: '2025' }, { name: 'total_revenue', label: 'Total Revenue', defaultValue: '' }, { name: 'total_expenses', label: 'Total Expenses', defaultValue: '' }, { name: 'reserve_balance', label: 'Reserve Balance', defaultValue: '' }, { name: 'fee', label: 'Current Monthly Assessment', defaultValue: '' }, { name: 'due_date', label: 'Next Assessment Due', defaultValue: '' }, { name: 'financial_highlights', label: 'Key Highlights', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }] },

    { id: 'lt20', name: 'Board Resignation / Appointment Notice', category: 'notice', subject: 'Board of Directors Update', body: 'Dear {{owner_name}},\n\nThe Board of Directors of {{building_name}} wishes to inform you of the following change:\n\n{{change_type}}: {{member_name}} has {{change_details}} the position of {{position}}, effective {{effective_date}}.\n\n{{replacement_info}}\n\nThe Board continues to serve the association and its {{total_units}} unit owners. Your current monthly assessment of {{fee}} remains unchanged. The next Board meeting is scheduled for {{due_date}}.\n\nIf you have questions, please contact the management office.\n\nSincerely,\n{{sender_name}}\n{{sender_title}}', variables: [{ name: 'owner_name', label: 'Owner Name', defaultValue: '' }, { name: 'building_name', label: 'Building Name', defaultValue: 'Sunny Acres Condominium' }, { name: 'change_type', label: 'Change Type', defaultValue: 'Resignation' }, { name: 'member_name', label: 'Member Name', defaultValue: '' }, { name: 'change_details', label: 'Details', defaultValue: 'resigned from' }, { name: 'position', label: 'Position', defaultValue: '' }, { name: 'effective_date', label: 'Effective Date', defaultValue: '' }, { name: 'replacement_info', label: 'Replacement Info', defaultValue: '' }, { name: 'total_units', label: 'Total Units', defaultValue: '50' }, { name: 'fee', label: 'Current Assessment', defaultValue: '' }, { name: 'due_date', label: 'Next Board Meeting', defaultValue: '' }, { name: 'sender_name', label: 'Sender Name', defaultValue: '' }, { name: 'sender_title', label: 'Sender Title', defaultValue: 'Board President' }] },
  ],
  letters: [],

  loadFromDb: async (tenantId: string) => {
    const [templates, letters] = await Promise.all([
      letterSvc.fetchTemplates(tenantId),
      letterSvc.fetchLetters(tenantId),
    ]);
    const updates: Partial<LetterState> = {};
    if (templates && templates.length > 0) updates.templates = templates;
    if (letters && letters.length > 0) updates.letters = letters;
    if (Object.keys(updates).length > 0) set(updates);
  },

  addTemplate: (t, tenantId?) => {
    const id = 'lt' + Date.now();
    set(s => ({ templates: [{ id, ...t }, ...s.templates] }));
    if (isBackendEnabled && tenantId) {
      letterSvc.createTemplate(tenantId, t).then(dbRow => {
        if (dbRow) set(s => ({ templates: s.templates.map(x => x.id === id ? { ...x, id: dbRow.id } : x) }));
      });
    }
  },

  updateTemplate: (id, updates) => {
    set(s => ({ templates: s.templates.map(t => t.id === id ? { ...t, ...updates } : t) }));
    if (isBackendEnabled) letterSvc.updateTemplate(id, updates);
  },

  deleteTemplate: (id) => {
    set(s => ({ templates: s.templates.filter(t => t.id !== id) }));
    if (isBackendEnabled) letterSvc.deleteTemplate(id);
  },

  addLetter: (l, tenantId?) => {
    const id = 'gl' + Date.now();
    set(s => ({ letters: [{ id, ...l }, ...s.letters] }));
    if (isBackendEnabled && tenantId) {
      letterSvc.createLetter(tenantId, l).then(dbRow => {
        if (dbRow) set(s => ({ letters: s.letters.map(x => x.id === id ? { ...x, id: dbRow.id } : x) }));
      });
    }
  },

  updateLetter: (id, updates) => {
    set(s => ({ letters: s.letters.map(l => l.id === id ? { ...l, ...updates } : l) }));
    if (isBackendEnabled) letterSvc.updateLetter(id, updates);
  },

  deleteLetter: (id) => {
    set(s => ({ letters: s.letters.filter(l => l.id !== id) }));
    if (isBackendEnabled) letterSvc.deleteLetter(id);
  },
}), {
  name: 'onetwo-letters',
  merge: (persisted: any, current: any) => {
    if (!persisted) return current;
    // Seed template IDs from code — always include these
    const seedIds = new Set(current.templates.map((t: any) => t.id));
    // Keep any user-created templates from localStorage (those with non-seed IDs)
    const userTemplates = (persisted.templates || []).filter((t: any) => !seedIds.has(t.id));
    return {
      ...current,
      ...persisted,
      // All seed templates (latest from code) + any user-created ones
      templates: [...current.templates, ...userTemplates],
    };
  },
}));
