import { useState } from 'react';
import { usePlatformAdminStore, generateSubdomain, TIER_FEATURES, type Tenant, type PlatformUser, type SubscriptionTier, type SupportTicket, type EmailTemplate } from '@/store/usePlatformAdminStore';
import { useAuthStore } from '@/store/useAuthStore';
import { fmt } from '@/lib/formatters';
import Modal from '@/components/ui/Modal';

const STATUS_BADGE: Record<string, string> = { active: 'bg-sage-100 text-sage-700', onboarding: 'bg-accent-100 text-accent-700', suspended: 'bg-red-100 text-red-700', archived: 'bg-ink-100 text-ink-500', trial: 'bg-yellow-100 text-yellow-700', past_due: 'bg-red-100 text-red-700', cancelled: 'bg-ink-100 text-ink-500' };
const TIER_BADGE: Record<string, string> = { essentials: 'bg-ink-100 text-ink-600', compliance_pro: 'bg-accent-100 text-accent-700', advanced_governance: 'bg-sage-100 text-sage-700' };
const TIER_PRICES: Record<SubscriptionTier, number> = { essentials: 49, compliance_pro: 179, advanced_governance: 299 };
const TIER_LABELS: Record<string, string> = { essentials: 'Essentials', compliance_pro: 'Compliance Pro', advanced_governance: 'Advanced Governance' };
const ROLE_BADGE: Record<string, string> = { super_admin: 'bg-red-100 text-red-700', support: 'bg-accent-100 text-accent-700', billing: 'bg-sage-100 text-sage-700', readonly: 'bg-ink-100 text-ink-500' };
const FEATURE_LABELS: Record<string, string> = { fiscalLens: 'Fiscal Lens', caseOps: 'Case Ops', complianceRunbook: 'Compliance Runbook', aiAdvisor: 'AI Advisor', documentVault: 'Document Vault', paymentProcessing: 'Payment Processing', votesResolutions: 'Votes & Resolutions', communityPortal: 'Community Portal', vendorManagement: 'Vendor Management', reserveStudyTools: 'Reserve Study Tools' };
const TKT_STATUS: Record<string, string> = { open: 'bg-red-100 text-red-700', in_progress: 'bg-accent-100 text-accent-700', waiting: 'bg-yellow-100 text-yellow-700', resolved: 'bg-sage-100 text-sage-700', closed: 'bg-ink-100 text-ink-500' };
const TKT_PRIO: Record<string, string> = { low: 'bg-ink-50 text-ink-500', medium: 'bg-yellow-50 text-yellow-700', high: 'bg-orange-100 text-orange-700', urgent: 'bg-red-100 text-red-700' };

function Toggle({ on, onChange }: { on: boolean; onChange: () => void }) {
  return <button onClick={onChange} className={`w-10 h-5 rounded-full relative transition-colors cursor-pointer ${on ? 'bg-sage-500' : 'bg-ink-200'}`}><div className={`absolute top-0.5 w-4 h-4 bg-white rounded-full transition-transform shadow-sm ${on ? 'left-[22px]' : 'left-0.5'}`} /></button>;
}

export default function PlatformAdminPage() {
  const store = usePlatformAdminStore();
  const { tenants, platformUsers, auditLog, supportTickets, announcements, emailTemplates, invoices, impersonating } = store;
  const { currentUser } = useAuthStore();
  const metrics = store.getPlatformMetrics();
  const ACTOR = currentUser?.name || 'Admin';

  const [tab, setTab] = useState('overview');
  const [selectedBldg, setSelectedBldg] = useState<string | null>(null);
  const [modal, setModal] = useState<string | null>(null);
  const [auditFilter, setAuditFilter] = useState('');

  // Forms
  const [bldgForm, setBldgForm] = useState({ name: '', street: '', city: '', state: '', zip: '', units: '', yearBuilt: '', contactName: '', contactEmail: '', contactPhone: '', tier: 'compliance_pro' as SubscriptionTier });
  const [userForm, setUserForm] = useState({ name: '', email: '', role: 'support' as PlatformUser['role'] });
  const [tktForm, setTktForm] = useState({ buildingId: '', subject: '', description: '', priority: 'medium' as SupportTicket['priority'] });
  const [tktNote, setTktNote] = useState('');
  const [selectedTkt, setSelectedTkt] = useState<string | null>(null);
  const [annForm, setAnnForm] = useState({ title: '', message: '', audience: 'all' });
  const [tmplEditId, setTmplEditId] = useState<string | null>(null);
  const [tmplForm, setTmplForm] = useState({ subject: '', body: '' });

  const handleAddBuilding = () => {
    if (!bldgForm.name || !bldgForm.contactEmail) { alert('Building name and contact email required'); return; }
    const id = `bld-${Date.now()}`; const today = new Date().toISOString().split('T')[0]; const trialEnd = new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0];
    const subdomain = generateSubdomain(bldgForm.name, tenants.map(t => t.subdomain));
    store.addTenant({ id, name: bldgForm.name, subdomain, address: { street: bldgForm.street, city: bldgForm.city, state: bldgForm.state, zip: bldgForm.zip }, totalUnits: parseInt(bldgForm.units) || 0, yearBuilt: bldgForm.yearBuilt, status: 'onboarding', createdAt: today, subscription: { tier: bldgForm.tier, status: 'trial', startDate: today, nextBillingDate: trialEnd, monthlyRate: TIER_PRICES[bldgForm.tier], trialEndsAt: trialEnd }, stats: { activeUsers: 0, occupiedUnits: 0, collectionRate: 0, complianceScore: 0, openCases: 0, monthlyRevenue: 0 }, primaryContact: { name: bldgForm.contactName, email: bldgForm.contactEmail, phone: bldgForm.contactPhone, role: 'Primary Contact' }, features: { ...TIER_FEATURES[bldgForm.tier] }, onboardingChecklist: { accountCreated: true, buildingProfileComplete: !!bldgForm.street, unitsConfigured: false, firstUserInvited: false, bylawsUploaded: false, financialSetupDone: false, goLive: false } });
    store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'building.create', target: bldgForm.name, details: `Onboarded: ${subdomain}.getonetwo.com — ${TIER_LABELS[bldgForm.tier]} trial`, buildingId: id });
    setBldgForm({ name: '', street: '', city: '', state: '', zip: '', units: '', yearBuilt: '', contactName: '', contactEmail: '', contactPhone: '', tier: 'compliance_pro' }); setModal(null);
  };

  const selected = tenants.find(t => t.id === selectedBldg);
  const openTickets = supportTickets.filter(t => t.status !== 'resolved' && t.status !== 'closed');
  const totalPaid = invoices.filter(i => i.status === 'paid').reduce((s, i) => s + i.amount, 0);
  const totalOverdue = invoices.filter(i => i.status === 'overdue').reduce((s, i) => s + i.amount, 0);

  const TABS = [
    { id: 'overview', label: '◎ Overview' },
    { id: 'buildings', label: '🏢 Buildings' },
    { id: 'onboarding', label: '🚀 Onboarding' },
    { id: 'tiers', label: '💎 Tiers' },
    { id: 'support', label: '🎧 Support', badge: openTickets.length || undefined },
    { id: 'config', label: '⚙️ Config' },
    { id: 'revenue', label: '💰 Revenue' },
    { id: 'health', label: '❤️ Health' },
    { id: 'users', label: '👤 Users' },
    { id: 'audit', label: '📋 Audit' },
  ];

  return (
    <div className="space-y-0">
      {/* Impersonation Banner */}
      {impersonating && (() => { const t = tenants.find(x => x.id === impersonating); return t ? (
        <div className="bg-yellow-400 text-yellow-900 px-4 py-2 flex items-center justify-between text-sm font-semibold"><span>👁 Viewing as: {t.name} ({t.subdomain}.getonetwo.com)</span><button onClick={() => { store.setImpersonating(null); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'impersonate.end', target: t.name, details: 'Stopped impersonating', buildingId: t.id }); }} className="px-3 py-1 bg-yellow-900 text-yellow-100 rounded text-xs">Exit View-As</button></div>
      ) : null; })()}

      <div className="bg-gradient-to-r from-ink-900 via-ink-800 to-red-900 rounded-t-xl p-6 text-white">
        <div className="flex items-center gap-3 mb-1"><span className="px-2 py-0.5 bg-red-500 bg-opacity-30 rounded text-xs font-bold uppercase">Platform Admin</span><span className="text-xs text-red-200">Logged in as {ACTOR}</span></div>
        <h2 className="font-display text-2xl font-bold">Multi-Tenancy Console</h2>
        <p className="text-red-200 text-sm mt-1">{metrics.totalBuildings} buildings · {metrics.totalUnits} units · {metrics.totalUsers} users · MRR {fmt(metrics.mrr)}</p>
      </div>

      <div className="bg-white border-x border-b border-ink-100 overflow-x-auto"><div className="flex min-w-max px-4">{TABS.map(t => (<button key={t.id} onClick={() => { setTab(t.id); setSelectedBldg(null); }} className={`px-3.5 py-3 text-sm font-medium border-b-2 whitespace-nowrap transition-colors flex items-center gap-1.5 ${tab === t.id ? 'border-red-600 text-ink-900' : 'border-transparent text-ink-400 hover:text-ink-700'}`}>{t.label}{t.badge && <span className="bg-red-500 text-white text-[10px] rounded-full px-1.5 py-0.5 font-bold">{t.badge}</span>}</button>))}</div></div>

      <div className="bg-white rounded-b-xl border-x border-b border-ink-100 p-6">

        {/* ═══ OVERVIEW ═══ */}
        {tab === 'overview' && (<div className="space-y-6">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{ label: 'Active Buildings', value: metrics.activeBuildings, sub: `of ${metrics.totalBuildings}` }, { label: 'MRR', value: fmt(metrics.mrr), sub: `ARR ${fmt(metrics.arr)}` }, { label: 'Platform Users', value: metrics.totalUsers, sub: 'all buildings' }, { label: 'Avg Compliance', value: `${metrics.avgCompliance}%`, sub: metrics.avgCompliance >= 80 ? 'Healthy' : 'Needs attention' }].map(m => (<div key={m.label} className="bg-white border border-ink-100 rounded-xl p-4"><p className="text-xs font-semibold text-ink-400 uppercase">{m.label}</p><p className="text-2xl font-bold text-ink-900 mt-1">{m.value}</p><p className="text-xs text-ink-400">{m.sub}</p></div>))}</div>
          {metrics.pastDueBuildings > 0 && <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-center gap-3"><span className="text-xl">⚠️</span><div><p className="font-semibold text-red-800">{metrics.pastDueBuildings} past due</p></div></div>}
          {openTickets.length > 0 && <div className="bg-accent-50 border border-accent-200 rounded-xl p-4 flex items-center gap-3 cursor-pointer" onClick={() => setTab('support')}><span className="text-xl">🎧</span><div><p className="font-semibold text-accent-800">{openTickets.length} open support ticket{openTickets.length !== 1 ? 's' : ''}</p><p className="text-xs text-accent-600">{openTickets.filter(t => t.priority === 'urgent').length} urgent</p></div></div>}
          <div><h3 className="font-display text-lg font-bold text-ink-900 mb-3">Subscription Mix</h3><div className="grid grid-cols-3 gap-3">{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(tier => { const count = tenants.filter(t => t.subscription.tier === tier).length; const rev = tenants.filter(t => t.subscription.tier === tier && ['active','trial'].includes(t.subscription.status)).reduce((s,t) => s + t.subscription.monthlyRate, 0); return (<div key={tier} className={`rounded-xl p-4 border ${TIER_BADGE[tier].split(' ')[0]}`}><p className="text-xs font-semibold uppercase">{TIER_LABELS[tier]}</p><p className="text-2xl font-bold text-ink-900 mt-1">{count}</p><p className="text-xs text-ink-500">{fmt(rev)}/mo</p></div>); })}</div></div>
          <div><h3 className="font-display text-lg font-bold text-ink-900 mb-3">All Buildings</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{tenants.map(t => (<div key={t.id} className="bg-white border border-ink-100 rounded-xl p-4 hover:shadow-md cursor-pointer" onClick={() => { setTab('buildings'); setSelectedBldg(t.id); }}><div className="flex items-center justify-between mb-2"><h4 className="font-semibold text-ink-900 truncate">{t.name}</h4><div className="flex gap-1.5 shrink-0"><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${STATUS_BADGE[t.status]}`}>{t.status}</span><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${TIER_BADGE[t.subscription.tier]}`}>{TIER_LABELS[t.subscription.tier]}</span></div></div><p className="text-xs text-accent-600 font-mono mb-1">{t.subdomain}.getonetwo.com</p><div className="grid grid-cols-4 gap-2 text-xs"><div><p className="text-ink-400">Units</p><p className="font-bold">{t.totalUnits}</p></div><div><p className="text-ink-400">Users</p><p className="font-bold">{t.stats.activeUsers}</p></div><div><p className="text-ink-400">Collect.</p><p className={`font-bold ${t.stats.collectionRate >= 90 ? 'text-sage-600' : 'text-red-600'}`}>{t.stats.collectionRate || '—'}%</p></div><div><p className="text-ink-400">MRR</p><p className="font-bold">{fmt(t.subscription.monthlyRate)}</p></div></div></div>))}</div></div>
        </div>)}

        {/* ═══ BUILDINGS ═══ */}
        {tab === 'buildings' && !selected && (<div className="space-y-4">
          <div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-ink-900">Buildings ({tenants.length})</h3><button onClick={() => setModal('addBldg')} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">+ Onboard</button></div>
          <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-ink-400 uppercase border-b border-ink-100"><th className="py-2 pr-3">Building</th><th className="py-2 pr-3">Subdomain</th><th className="py-2 pr-3">Status</th><th className="py-2 pr-3">Tier</th><th className="py-2 pr-3 text-right">Units</th><th className="py-2 pr-3 text-right">MRR</th><th className="py-2">Contact</th></tr></thead><tbody>{tenants.map(t => (<tr key={t.id} className="border-b border-ink-50 hover:bg-mist-50 cursor-pointer" onClick={() => setSelectedBldg(t.id)}><td className="py-3 pr-3"><p className="font-semibold text-ink-900">{t.name}</p></td><td className="py-3 pr-3"><span className="text-xs font-mono text-accent-600">{t.subdomain}.getonetwo.com</span></td><td className="py-3 pr-3"><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${STATUS_BADGE[t.status]}`}>{t.status}</span></td><td className="py-3 pr-3"><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${TIER_BADGE[t.subscription.tier]}`}>{TIER_LABELS[t.subscription.tier]}</span></td><td className="py-3 pr-3 text-right">{t.totalUnits}</td><td className="py-3 pr-3 text-right font-semibold">{fmt(t.subscription.monthlyRate)}</td><td className="py-3 text-xs text-ink-500">{t.primaryContact.name}</td></tr>))}</tbody></table></div>
        </div>)}
        {tab === 'buildings' && selected && (<div className="space-y-6">
          <button onClick={() => setSelectedBldg(null)} className="text-sm text-accent-600 font-medium">← Back</button>
          <div className="flex items-start justify-between flex-wrap gap-3"><div><h3 className="font-display text-2xl font-bold text-ink-900">{selected.name}</h3><p className="text-sm text-ink-500">{selected.address.street}, {selected.address.city}, {selected.address.state} {selected.address.zip}</p><p className="text-xs text-accent-600 font-mono mt-1">🌐 {selected.subdomain}.getonetwo.com</p></div><div className="flex gap-2 shrink-0"><span className={`pill px-3 py-1 rounded text-sm font-semibold ${STATUS_BADGE[selected.status]}`}>{selected.status}</span><span className={`pill px-3 py-1 rounded text-sm font-semibold ${TIER_BADGE[selected.subscription.tier]}`}>{TIER_LABELS[selected.subscription.tier]}</span></div></div>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">{[{ l: 'Units', v: selected.totalUnits }, { l: 'Occupied', v: selected.stats.occupiedUnits }, { l: 'Users', v: selected.stats.activeUsers }, { l: 'Collection', v: `${selected.stats.collectionRate}%` }, { l: 'Compliance', v: `${selected.stats.complianceScore}%` }, { l: 'Cases', v: selected.stats.openCases }].map(s => (<div key={s.l} className="bg-mist-50 rounded-lg p-3"><p className="text-xs text-ink-400">{s.l}</p><p className="text-lg font-bold text-ink-900">{s.v}</p></div>))}</div>
          {/* Actions with Impersonate */}
          <div className="bg-white border border-ink-100 rounded-xl p-5"><h4 className="font-bold text-ink-900 mb-3">Actions</h4><div className="flex gap-2 flex-wrap">
            <button onClick={() => { store.setImpersonating(selected.id); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'impersonate.start', target: selected.name, details: `Viewing as ${selected.name}`, buildingId: selected.id }); }} className="px-4 py-2 bg-yellow-500 text-white rounded-lg text-sm font-medium hover:bg-yellow-600">👁 View as Tenant</button>
            {selected.status !== 'active' && <button onClick={() => { store.updateTenantStatus(selected.id, 'active'); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'building.activate', target: selected.name, details: 'Activated', buildingId: selected.id }); }} className="px-4 py-2 bg-sage-600 text-white rounded-lg text-sm font-medium">✓ Activate</button>}
            {selected.status !== 'suspended' && <button onClick={() => { store.updateTenantStatus(selected.id, 'suspended'); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'building.suspend', target: selected.name, details: 'Suspended', buildingId: selected.id }); }} className="px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-medium">⛔ Suspend</button>}
            {selected.status === 'onboarding' && <button onClick={() => { store.updateTenantStatus(selected.id, 'active'); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'building.activate', target: selected.name, details: 'Onboarding complete', buildingId: selected.id }); }} className="px-4 py-2 bg-accent-600 text-white rounded-lg text-sm font-medium">🚀 Complete Onboarding</button>}
          </div></div>
          {/* Subscription */}
          <div className="bg-accent-50 border border-accent-200 rounded-xl p-5"><h4 className="font-bold text-ink-900 mb-3">Subscription</h4><div className="grid grid-cols-5 gap-4 text-sm mb-4"><div><p className="text-xs text-ink-400">Tier</p><p className="font-bold">{TIER_LABELS[selected.subscription.tier]}</p></div><div><p className="text-xs text-ink-400">Status</p><p className="font-bold capitalize">{selected.subscription.status.replace('_',' ')}</p></div><div><p className="text-xs text-ink-400">Rate</p><p className="font-bold">{fmt(selected.subscription.monthlyRate)}/mo</p></div><div><p className="text-xs text-ink-400">Start</p><p className="font-bold">{selected.subscription.startDate}</p></div><div><p className="text-xs text-ink-400">Next Billing</p><p className="font-bold">{selected.subscription.nextBillingDate}</p></div></div><div className="flex gap-2 flex-wrap">{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).filter(t => t !== selected.subscription.tier).map(tier => (<button key={tier} onClick={() => store.changeTier(selected.id, tier, ACTOR)} className="px-3 py-1.5 border border-ink-200 rounded-lg text-xs font-medium">→ {TIER_LABELS[tier]} ({fmt(TIER_PRICES[tier])})</button>))}{selected.subscription.status === 'past_due' && <button onClick={() => { store.updateSubscription(selected.id, { status: 'active' }); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'subscription.resolve', target: selected.name, details: 'Resolved', buildingId: selected.id }); }} className="px-3 py-1.5 bg-sage-600 text-white rounded-lg text-xs font-medium">✓ Mark Paid</button>}</div><p className="text-[10px] text-ink-400 mt-3">Tier change auto-updates feature flags.</p></div>
          {/* Features */}
          <div className="bg-white border border-ink-100 rounded-xl p-5"><h4 className="font-bold text-ink-900 mb-3">Feature Flags</h4><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{(Object.entries(selected.features) as [keyof Tenant['features'], boolean][]).map(([key, enabled]) => { const tierDefault = TIER_FEATURES[selected.subscription.tier][key]; const isOverride = enabled !== tierDefault; return (<div key={key} className={`flex items-center justify-between py-2.5 px-3 rounded-lg ${isOverride ? 'bg-yellow-50 border border-yellow-200' : 'bg-mist-50'}`}><div><span className="text-sm font-medium text-ink-700">{FEATURE_LABELS[key] || key}</span>{isOverride && <span className="ml-1.5 text-[9px] bg-yellow-200 text-yellow-800 px-1 py-0.5 rounded font-bold">OVERRIDE</span>}</div><Toggle on={enabled} onChange={() => { store.toggleFeature(selected.id, key); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'feature.toggle', target: selected.name, details: `${enabled ? 'Disabled' : 'Enabled'} ${FEATURE_LABELS[key]}`, buildingId: selected.id }); }} /></div>); })}</div></div>
          {/* Onboarding Checklist */}
          <div className="bg-white border border-ink-100 rounded-xl p-5"><h4 className="font-bold text-ink-900 mb-3">Onboarding</h4><div className="space-y-2">{(Object.entries(selected.onboardingChecklist) as [keyof Tenant['onboardingChecklist'], boolean][]).map(([step, done]) => { const labels: Record<string, string> = { accountCreated: 'Account created', buildingProfileComplete: 'Profile complete', unitsConfigured: 'Units configured', firstUserInvited: 'First user invited', bylawsUploaded: 'Bylaws uploaded', financialSetupDone: 'Financials set up', goLive: 'Go-live' }; return (<label key={step} className="flex items-center gap-3 p-2 rounded-lg hover:bg-mist-50 cursor-pointer"><input type="checkbox" checked={done} onChange={() => store.updateOnboardingStep(selected.id, step, !done)} className="h-4 w-4" /><span className={`text-sm ${done ? 'text-ink-500 line-through' : 'text-ink-900 font-medium'}`}>{labels[step]}</span></label>); })}</div></div>
          {/* Invoices for this building */}
          {invoices.filter(i => i.buildingId === selected.id).length > 0 && <div><h4 className="font-bold text-ink-900 mb-3">Invoices</h4><div className="space-y-1">{invoices.filter(i => i.buildingId === selected.id).map(i => (<div key={i.id} className="flex items-center justify-between py-2 border-b border-ink-50 text-sm"><span className="text-ink-500">{i.date}</span><span className="font-semibold">{fmt(i.amount)}</span><span className={`pill px-2 py-0.5 rounded text-xs ${i.status === 'paid' ? 'bg-sage-100 text-sage-700' : 'bg-red-100 text-red-700'}`}>{i.status}</span></div>))}</div></div>}
          {/* Building audit */}
          <div><h4 className="font-bold text-ink-900 mb-3">Audit Trail</h4><div className="bg-white border border-ink-100 rounded-xl overflow-hidden">{auditLog.filter(e => e.buildingId === selected.id).length === 0 ? <p className="p-4 text-sm text-ink-400">No entries.</p> : <div className="divide-y divide-ink-50">{auditLog.filter(e => e.buildingId === selected.id).slice(0, 10).map(e => (<div key={e.id} className="flex items-center gap-3 px-4 py-2.5 text-sm"><span className="text-xs text-ink-300 w-28 shrink-0">{new Date(e.timestamp).toLocaleDateString()}</span><span className="font-mono text-xs text-ink-400">{e.action}</span><span className="text-ink-600 truncate">{e.details}</span></div>))}</div>}</div></div>
        </div>)}

        {/* ═══ ONBOARDING ═══ */}
        {tab === 'onboarding' && (<div className="space-y-6">
          <div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-ink-900">🚀 Onboarding Pipeline</h3><button onClick={() => setModal('addBldg')} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">+ Onboard</button></div>
          <div className="bg-mist-50 border border-mist-200 rounded-xl p-5"><p className="text-xs text-ink-400">When onboarded: subdomain provisioned at <strong>[name].getonetwo.com</strong>, features set to tier defaults, checklist initiated, welcome email queued.</p></div>
          {tenants.filter(t => t.status === 'onboarding').length === 0 ? <p className="text-sm text-ink-400 text-center py-8">No buildings onboarding.</p> : tenants.filter(t => t.status === 'onboarding').map(t => { const steps = Object.values(t.onboardingChecklist); const done = steps.filter(Boolean).length; const pct = Math.round((done / steps.length) * 100); return (<div key={t.id} className="bg-white border border-accent-200 rounded-xl p-5"><div className="flex items-center justify-between mb-3"><div><h4 className="font-semibold text-ink-900">{t.name}</h4><p className="text-xs text-accent-600 font-mono">{t.subdomain}.getonetwo.com</p></div><div className="text-right"><p className="text-sm font-bold">{pct}%</p><p className="text-[10px] text-ink-400">{done}/{steps.length}</p></div></div><div className="w-full h-2 bg-ink-100 rounded-full mb-3"><div className="h-full bg-accent-500 rounded-full" style={{ width: `${pct}%` }} /></div>{pct === 100 && <button onClick={() => { store.updateTenantStatus(t.id, 'active'); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'building.activate', target: t.name, details: 'Go-live', buildingId: t.id }); }} className="mt-2 px-4 py-2 bg-sage-600 text-white rounded-lg text-sm font-medium w-full">🚀 Go Live</button>}</div>); })}
          {tenants.filter(t => t.subscription.status === 'trial').length > 0 && <div><h3 className="font-bold text-ink-900 mb-3">Active Trials</h3>{tenants.filter(t => t.subscription.status === 'trial').map(t => { const daysLeft = Math.max(0, Math.ceil((new Date(t.subscription.trialEndsAt || '').getTime() - Date.now()) / 86400000)); return (<div key={t.id} className="bg-yellow-50 border border-yellow-200 rounded-xl p-4 flex items-center justify-between mb-2"><div><p className="font-semibold text-ink-900">{t.name}</p><p className="text-xs text-yellow-700">{TIER_LABELS[t.subscription.tier]} · {daysLeft}d left</p></div><span className={`text-sm font-bold ${daysLeft <= 7 ? 'text-red-600' : 'text-yellow-700'}`}>{daysLeft}d</span></div>); })}</div>}
        </div>)}

        {/* ═══ TIERS ═══ */}
        {tab === 'tiers' && (<div className="space-y-6">
          <h3 className="font-display text-lg font-bold text-ink-900">💎 Tiers & Feature Matrix</h3>
          <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-ink-400 uppercase border-b border-ink-200"><th className="py-3 pr-6 w-48">Feature</th>{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(t => <th key={t} className="py-3 px-4 text-center"><span className={`pill px-2.5 py-1 rounded text-xs font-bold ${TIER_BADGE[t]}`}>{TIER_LABELS[t]}</span><p className="text-lg font-bold text-ink-900 mt-1">{fmt(TIER_PRICES[t])}/mo</p></th>)}</tr></thead><tbody>{Object.keys(TIER_FEATURES.essentials).map(feat => (<tr key={feat} className="border-b border-ink-50"><td className="py-3 pr-6 font-medium text-ink-700">{FEATURE_LABELS[feat]}</td>{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(t => <td key={t} className="py-3 px-4 text-center"><span className={`text-lg ${TIER_FEATURES[t][feat as keyof Tenant['features']] ? 'text-sage-600' : 'text-ink-200'}`}>{TIER_FEATURES[t][feat as keyof Tenant['features']] ? '✓' : '—'}</span></td>)}</tr>))}</tbody></table></div>
          <div><h4 className="font-bold text-ink-900 mb-3">Buildings by Tier</h4><div className="grid grid-cols-3 gap-4">{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(tier => (<div key={tier} className={`rounded-xl p-4 border ${TIER_BADGE[tier].split(' ')[0]}`}><p className="text-xs font-bold uppercase mb-2">{TIER_LABELS[tier]}</p>{tenants.filter(t => t.subscription.tier === tier).map(t => (<div key={t.id} className="flex items-center justify-between py-1.5"><span className="text-sm text-ink-700">{t.name}</span><span className={`text-[10px] px-1.5 py-0.5 rounded ${STATUS_BADGE[t.status]}`}>{t.status}</span></div>))}</div>))}</div></div>
        </div>)}

        {/* ═══ SUPPORT ═══ */}
        {tab === 'support' && !selectedTkt && (<div className="space-y-4">
          <div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-ink-900">🎧 Support Tickets ({supportTickets.length})</h3><button onClick={() => { setTktForm({ buildingId: '', subject: '', description: '', priority: 'medium' }); setModal('addTicket'); }} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">+ New Ticket</button></div>
          <div className="grid grid-cols-4 gap-3">{[{ l: 'Open', c: supportTickets.filter(t => t.status === 'open').length, color: 'red' }, { l: 'In Progress', c: supportTickets.filter(t => t.status === 'in_progress').length, color: 'accent' }, { l: 'Waiting', c: supportTickets.filter(t => t.status === 'waiting').length, color: 'yellow' }, { l: 'Resolved', c: supportTickets.filter(t => t.status === 'resolved' || t.status === 'closed').length, color: 'sage' }].map(s => <div key={s.l} className="bg-mist-50 rounded-lg p-3 text-center"><p className={`text-2xl font-bold text-${s.color}-600`}>{s.c}</p><p className="text-xs text-ink-400">{s.l}</p></div>)}</div>
          <div className="space-y-2">{supportTickets.map(t => (<div key={t.id} className="bg-white border border-ink-100 rounded-xl p-4 hover:shadow-sm cursor-pointer" onClick={() => setSelectedTkt(t.id)}>
            <div className="flex items-start justify-between gap-3"><div className="flex-1"><div className="flex items-center gap-2 mb-1"><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${TKT_PRIO[t.priority]}`}>{t.priority}</span><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${TKT_STATUS[t.status]}`}>{t.status.replace('_',' ')}</span><p className="font-semibold text-ink-900">{t.subject}</p></div><p className="text-xs text-ink-500">{t.buildingName} · by {t.createdBy} · {new Date(t.createdAt).toLocaleDateString()}</p></div>{t.assignedTo && <span className="text-xs bg-mist-100 px-2 py-1 rounded shrink-0">{t.assignedTo}</span>}</div>
          </div>))}</div>
        </div>)}
        {tab === 'support' && selectedTkt && (() => { const t = supportTickets.find(x => x.id === selectedTkt); if (!t) return null; return (<div className="space-y-4">
          <button onClick={() => setSelectedTkt(null)} className="text-sm text-accent-600 font-medium">← Back</button>
          <div className="flex items-start justify-between"><div><h3 className="text-xl font-bold text-ink-900">{t.subject}</h3><p className="text-sm text-ink-500">{t.buildingName} · {t.createdBy} · {new Date(t.createdAt).toLocaleString()}</p></div><div className="flex gap-2"><span className={`pill px-2 py-1 rounded text-xs font-bold ${TKT_PRIO[t.priority]}`}>{t.priority}</span><span className={`pill px-2 py-1 rounded text-xs font-bold ${TKT_STATUS[t.status]}`}>{t.status.replace('_',' ')}</span></div></div>
          <div className="bg-mist-50 rounded-xl p-4 text-sm text-ink-700">{t.description}</div>
          <div className="flex gap-2 flex-wrap">
            <select value={t.status} onChange={e => store.updateTicket(t.id, { status: e.target.value as SupportTicket['status'] })} className="px-3 py-1.5 border border-ink-200 rounded-lg text-xs"><option value="open">Open</option><option value="in_progress">In Progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select>
            <select value={t.assignedTo || ''} onChange={e => store.updateTicket(t.id, { assignedTo: e.target.value || null })} className="px-3 py-1.5 border border-ink-200 rounded-lg text-xs"><option value="">Unassigned</option>{platformUsers.filter(u => u.status === 'active').map(u => <option key={u.id} value={u.name}>{u.name}</option>)}</select>
            <button onClick={() => { store.setImpersonating(t.buildingId); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'impersonate.start', target: t.buildingName, details: `Impersonating for ticket ${t.id}`, buildingId: t.buildingId }); }} className="px-3 py-1.5 bg-yellow-500 text-white rounded-lg text-xs font-medium">👁 View as Tenant</button>
          </div>
          {t.notes.length > 0 && <div><h4 className="font-bold text-ink-900 mb-2">Notes</h4><div className="space-y-2">{t.notes.map((n, i) => (<div key={i} className="bg-white border border-ink-100 rounded-lg p-3"><div className="flex items-center gap-2 mb-1"><span className="text-xs font-semibold text-ink-700">{n.author}</span><span className="text-[10px] text-ink-400">{new Date(n.date).toLocaleString()}</span></div><p className="text-sm text-ink-600">{n.text}</p></div>))}</div></div>}
          <div className="flex gap-2"><input value={tktNote} onChange={e => setTktNote(e.target.value)} placeholder="Add a note..." className="flex-1 px-3 py-2 border border-ink-200 rounded-lg text-sm" onKeyDown={e => { if (e.key === 'Enter' && tktNote.trim()) { store.addTicketNote(t.id, ACTOR, tktNote.trim()); setTktNote(''); } }} /><button onClick={() => { if (tktNote.trim()) { store.addTicketNote(t.id, ACTOR, tktNote.trim()); setTktNote(''); } }} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">Add</button></div>
        </div>); })()}

        {/* ═══ CONFIG ═══ */}
        {tab === 'config' && (<div className="space-y-6">
          <h3 className="font-display text-lg font-bold text-ink-900">⚙️ System Configuration</h3>
          {/* Email Templates */}
          <div><h4 className="font-bold text-ink-900 mb-3">Email Templates</h4><p className="text-xs text-ink-400 mb-3">Templates use {'{{'}variable{'}}'}  placeholders. Used for automated and manual communications.</p><div className="space-y-2">{emailTemplates.map(t => (<div key={t.id} className="bg-white border border-ink-100 rounded-xl p-4"><div className="flex items-center justify-between mb-2"><div><p className="font-semibold text-ink-900">{t.name}</p><p className="text-xs text-ink-400">Trigger: <span className="font-mono text-accent-600">{t.trigger}</span> · Last edited {t.lastEdited}</p></div><button onClick={() => { setTmplEditId(t.id); setTmplForm({ subject: t.subject, body: t.body }); setModal('editTemplate'); }} className="px-3 py-1.5 border border-ink-200 rounded-lg text-xs font-medium">Edit</button></div><p className="text-xs text-ink-500 font-mono bg-mist-50 rounded p-2">Subject: {t.subject}</p></div>))}</div></div>
          {/* Announcements */}
          <div><div className="flex items-center justify-between mb-3"><h4 className="font-bold text-ink-900">Announcements</h4><button onClick={() => { setAnnForm({ title: '', message: '', audience: 'all' }); setModal('addAnn'); }} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">+ New</button></div><div className="space-y-2">{announcements.map(a => (<div key={a.id} className="bg-white border border-ink-100 rounded-xl p-4 flex items-start justify-between"><div className="flex-1"><div className="flex items-center gap-2 mb-1"><p className="font-semibold text-ink-900">{a.title}</p><span className={`pill px-2 py-0.5 rounded text-xs ${a.status === 'sent' ? 'bg-sage-100 text-sage-700' : 'bg-yellow-100 text-yellow-700'}`}>{a.status}</span><span className="text-xs text-ink-400">→ {a.audience === 'all' ? 'All buildings' : TIER_LABELS[a.audience] || a.audience}</span></div><p className="text-xs text-ink-500">{a.message.slice(0, 120)}{a.message.length > 120 ? '...' : ''}</p><p className="text-[10px] text-ink-400 mt-1">by {a.createdBy} · {a.createdAt}{a.sentAt ? ` · sent ${a.sentAt}` : ''}</p></div><div className="flex gap-1 shrink-0">{a.status === 'draft' && <button onClick={() => { store.sendAnnouncement(a.id); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'announcement.send', target: a.title, details: `Sent to ${a.audience}`, buildingId: null }); }} className="px-3 py-1.5 bg-sage-600 text-white rounded-lg text-xs font-medium">Send</button>}<button onClick={() => store.deleteAnnouncement(a.id)} className="text-xs text-red-400 px-2">×</button></div></div>))}</div></div>
          {/* Default Feature Sets */}
          <div><h4 className="font-bold text-ink-900 mb-3">Default Feature Sets per Tier</h4><p className="text-xs text-ink-400 mb-3">These defaults are applied when a building is onboarded or changes tier. Individual buildings can override.</p><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-ink-400 uppercase border-b border-ink-100"><th className="py-2 pr-4">Feature</th>{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(t => <th key={t} className="py-2 px-3 text-center">{TIER_LABELS[t]}</th>)}</tr></thead><tbody>{Object.keys(TIER_FEATURES.essentials).map(feat => (<tr key={feat} className="border-b border-ink-50"><td className="py-2 pr-4 text-ink-700">{FEATURE_LABELS[feat]}</td>{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(t => <td key={t} className="py-2 px-3 text-center">{TIER_FEATURES[t][feat as keyof Tenant['features']] ? <span className="text-sage-600">✓</span> : <span className="text-ink-200">—</span>}</td>)}</tr>))}</tbody></table></div></div>
        </div>)}

        {/* ═══ REVENUE ═══ */}
        {tab === 'revenue' && (<div className="space-y-6">
          <h3 className="font-display text-lg font-bold text-ink-900">💰 Revenue & Billing</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{ l: 'MRR', v: fmt(metrics.mrr), sub: 'Monthly recurring' }, { l: 'ARR', v: fmt(metrics.arr), sub: 'Annual projection' }, { l: 'Collected', v: fmt(totalPaid), sub: 'This period' }, { l: 'Overdue', v: fmt(totalOverdue), sub: `${invoices.filter(i => i.status === 'overdue').length} invoices`, color: totalOverdue > 0 ? 'text-red-600' : '' }].map(m => (<div key={m.l} className="bg-white border border-ink-100 rounded-xl p-4"><p className="text-xs font-semibold text-ink-400 uppercase">{m.l}</p><p className={`text-2xl font-bold mt-1 ${(m as any).color || 'text-ink-900'}`}>{m.v}</p><p className="text-xs text-ink-400">{m.sub}</p></div>))}</div>
          {/* Revenue by tier */}
          <div><h4 className="font-bold text-ink-900 mb-3">Revenue by Tier</h4><div className="grid grid-cols-3 gap-3">{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(tier => { const bldgs = tenants.filter(t => t.subscription.tier === tier && ['active','trial'].includes(t.subscription.status)); const rev = bldgs.reduce((s,t) => s + t.subscription.monthlyRate, 0); const pct = metrics.mrr > 0 ? Math.round((rev / metrics.mrr) * 100) : 0; return (<div key={tier} className="bg-mist-50 rounded-xl p-4"><p className="text-xs font-bold uppercase text-ink-500">{TIER_LABELS[tier]}</p><p className="text-xl font-bold text-ink-900 mt-1">{fmt(rev)}/mo</p><p className="text-xs text-ink-400">{bldgs.length} buildings · {pct}% of MRR</p><div className="w-full h-1.5 bg-ink-100 rounded-full mt-2"><div className="h-full bg-accent-500 rounded-full" style={{ width: `${pct}%` }} /></div></div>); })}</div></div>
          {/* Invoices */}
          <div><h4 className="font-bold text-ink-900 mb-3">Recent Invoices</h4><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-ink-400 uppercase border-b border-ink-100"><th className="py-2 pr-3">Invoice</th><th className="py-2 pr-3">Building</th><th className="py-2 pr-3">Date</th><th className="py-2 pr-3">Due</th><th className="py-2 pr-3 text-right">Amount</th><th className="py-2 pr-3">Status</th><th className="py-2">Paid</th></tr></thead><tbody>{invoices.sort((a, b) => b.date.localeCompare(a.date)).map(i => (<tr key={i.id} className="border-b border-ink-50"><td className="py-2.5 pr-3 font-mono text-xs text-ink-400">{i.id}</td><td className="py-2.5 pr-3 text-ink-700">{i.buildingName}</td><td className="py-2.5 pr-3 text-xs text-ink-500">{i.date}</td><td className="py-2.5 pr-3 text-xs text-ink-500">{i.dueDate}</td><td className="py-2.5 pr-3 text-right font-semibold">{fmt(i.amount)}</td><td className="py-2.5 pr-3"><span className={`pill px-2 py-0.5 rounded text-xs ${i.status === 'paid' ? 'bg-sage-100 text-sage-700' : i.status === 'overdue' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'}`}>{i.status}</span></td><td className="py-2.5 text-xs text-ink-500">{i.paidDate || '—'}</td></tr>))}</tbody></table></div></div>
        </div>)}

        {/* ═══ HEALTH ═══ */}
        {tab === 'health' && (<div className="space-y-6">
          <h3 className="font-display text-lg font-bold text-ink-900">❤️ Tenant Health</h3>
          <div className="grid grid-cols-3 gap-4"><div className="bg-sage-50 border border-sage-200 rounded-xl p-4 text-center"><p className="text-3xl font-bold text-sage-700">{tenants.filter(t => t.stats.complianceScore >= 80).length}</p><p className="text-xs text-sage-600">Healthy (≥80%)</p></div><div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4 text-center"><p className="text-3xl font-bold text-yellow-700">{tenants.filter(t => t.stats.complianceScore >= 50 && t.stats.complianceScore < 80).length}</p><p className="text-xs text-yellow-600">At Risk (50-79%)</p></div><div className="bg-red-50 border border-red-200 rounded-xl p-4 text-center"><p className="text-3xl font-bold text-red-700">{tenants.filter(t => t.stats.complianceScore < 50 && t.status === 'active').length}</p><p className="text-xs text-red-600">Critical ({'<'}50%)</p></div></div>
          <div className="space-y-2">{tenants.filter(t => t.status !== 'archived').sort((a, b) => a.stats.complianceScore - b.stats.complianceScore).map(t => { const c = t.stats.complianceScore; const color = c >= 80 ? 'sage' : c >= 50 ? 'yellow' : 'red'; return (<div key={t.id} className="bg-white border border-ink-100 rounded-xl p-4 flex items-center gap-4"><div className="flex-1"><div className="flex items-center gap-2 mb-1"><p className="font-semibold text-ink-900">{t.name}</p><span className={`pill px-2 py-0.5 rounded text-xs ${STATUS_BADGE[t.status]}`}>{t.status}</span></div><div className="grid grid-cols-5 gap-3 text-xs"><div><p className="text-ink-400">Compliance</p><p className={`font-bold text-${color}-600`}>{c || '—'}%</p></div><div><p className="text-ink-400">Collection</p><p className={`font-bold ${t.stats.collectionRate >= 90 ? 'text-sage-600' : 'text-red-600'}`}>{t.stats.collectionRate || '—'}%</p></div><div><p className="text-ink-400">Users</p><p className="font-bold">{t.stats.activeUsers}</p></div><div><p className="text-ink-400">Cases</p><p className="font-bold">{t.stats.openCases}</p></div><div><p className="text-ink-400">MRR</p><p className="font-bold">{fmt(t.subscription.monthlyRate)}</p></div></div></div><div className="w-20 shrink-0"><div className="w-full h-2 bg-ink-100 rounded-full"><div className={`h-full bg-${color}-500 rounded-full`} style={{ width: `${c}%` }} /></div><p className={`text-center text-xs font-bold mt-1 text-${color}-600`}>{c}%</p></div></div>); })}</div>
        </div>)}

        {/* ═══ USERS ═══ */}
        {tab === 'users' && (<div className="space-y-4">
          <div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-ink-900">Platform Users ({platformUsers.length})</h3><button onClick={() => { setUserForm({ name: '', email: '', role: 'support' }); setModal('addUser'); }} className="px-4 py-2 bg-ink-900 text-white rounded-lg text-sm font-medium">+ Add</button></div>
          <div className="space-y-3">{platformUsers.map(u => (<div key={u.id} className="bg-white border border-ink-100 rounded-xl p-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className={`h-10 w-10 rounded-full ${u.status === 'active' ? 'bg-ink-900' : 'bg-ink-300'} flex items-center justify-center shrink-0`}><span className="text-white font-bold text-sm">{u.name.split(' ').map(n => n[0]).join('')}</span></div><div><div className="flex items-center gap-2"><p className="font-semibold text-ink-900">{u.name}</p><span className={`pill px-2 py-0.5 rounded text-xs font-semibold ${ROLE_BADGE[u.role]}`}>{u.role.replace('_',' ')}</span></div><p className="text-xs text-ink-500">{u.email}</p><p className="text-xs text-ink-400">Last: {u.lastLogin ? new Date(u.lastLogin).toLocaleDateString() : 'Never'}</p></div></div><button onClick={() => { if(confirm(`Remove ${u.name}?`)) { store.removePlatformUser(u.id); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'user.remove', target: u.name, details: `Removed (${u.role})`, buildingId: null }); }}} className="text-xs text-red-500">Remove</button></div>))}</div>
        </div>)}

        {/* ═══ AUDIT ═══ */}
        {tab === 'audit' && (<div className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-3"><h3 className="font-display text-lg font-bold text-ink-900">Audit Log ({auditLog.length})</h3><input value={auditFilter} onChange={e => setAuditFilter(e.target.value)} placeholder="Filter..." className="px-3 py-2 border border-ink-200 rounded-lg text-sm w-72" /></div>
          <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-ink-400 uppercase border-b border-ink-100"><th className="py-2 pr-3 w-40">Timestamp</th><th className="py-2 pr-3">Actor</th><th className="py-2 pr-3">Role</th><th className="py-2 pr-3">Action</th><th className="py-2 pr-3">Target</th><th className="py-2">Details</th></tr></thead><tbody>{auditLog.filter(e => !auditFilter || [e.actor, e.action, e.target, e.details].some(f => f.toLowerCase().includes(auditFilter.toLowerCase()))).map(e => (<tr key={e.id} className="border-b border-ink-50 hover:bg-mist-50"><td className="py-2.5 pr-3 text-xs text-ink-400 whitespace-nowrap">{new Date(e.timestamp).toLocaleString()}</td><td className="py-2.5 pr-3 font-medium text-ink-900 whitespace-nowrap">{e.actor}</td><td className="py-2.5 pr-3"><span className={`pill px-1.5 py-0.5 rounded text-xs ${ROLE_BADGE[e.actorRole]}`}>{e.actorRole.replace('_',' ')}</span></td><td className="py-2.5 pr-3 text-ink-600 font-mono text-xs whitespace-nowrap">{e.action}</td><td className="py-2.5 pr-3 text-ink-700 whitespace-nowrap">{e.target}</td><td className="py-2.5 text-ink-500 truncate max-w-xs">{e.details}</td></tr>))}</tbody></table></div>
        </div>)}
      </div>

      {/* ═══ MODALS ═══ */}
      {modal === 'addBldg' && (<Modal title="Onboard New Building" subtitle="Provisions subdomain and starts trial" onClose={() => setModal(null)} onSave={handleAddBuilding} saveLabel="Create & Provision" wide>
        <div className="space-y-4">
          <div className="border-b border-ink-100 pb-2"><p className="text-xs font-semibold text-ink-400 uppercase">Building</p></div>
          <div><label className="block text-sm font-medium text-ink-700 mb-1">Name *</label><input value={bldgForm.name} onChange={e => setBldgForm({...bldgForm, name: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" placeholder="Sunny Acres Condominium" /></div>
          {bldgForm.name && <div className="bg-accent-50 border border-accent-200 rounded-lg p-3"><p className="text-xs text-accent-800">🌐 <strong className="font-mono">{generateSubdomain(bldgForm.name, tenants.map(t => t.subdomain))}.getonetwo.com</strong></p></div>}
          <div><label className="block text-sm font-medium text-ink-700 mb-1">Street</label><input value={bldgForm.street} onChange={e => setBldgForm({...bldgForm, street: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div>
          <div className="grid grid-cols-3 gap-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">City</label><input value={bldgForm.city} onChange={e => setBldgForm({...bldgForm, city: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">State</label><input value={bldgForm.state} onChange={e => setBldgForm({...bldgForm, state: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" maxLength={2} /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">ZIP</label><input value={bldgForm.zip} onChange={e => setBldgForm({...bldgForm, zip: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div></div>
          <div className="grid grid-cols-2 gap-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">Units</label><input type="number" value={bldgForm.units} onChange={e => setBldgForm({...bldgForm, units: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Year Built</label><input value={bldgForm.yearBuilt} onChange={e => setBldgForm({...bldgForm, yearBuilt: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div></div>
          <div className="border-b border-ink-100 pb-2 mt-2"><p className="text-xs font-semibold text-ink-400 uppercase">Primary Contact</p></div>
          <div><label className="block text-sm font-medium text-ink-700 mb-1">Name</label><input value={bldgForm.contactName} onChange={e => setBldgForm({...bldgForm, contactName: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div>
          <div className="grid grid-cols-2 gap-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">Email *</label><input value={bldgForm.contactEmail} onChange={e => setBldgForm({...bldgForm, contactEmail: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Phone</label><input value={bldgForm.contactPhone} onChange={e => setBldgForm({...bldgForm, contactPhone: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div></div>
          <div className="border-b border-ink-100 pb-2 mt-2"><p className="text-xs font-semibold text-ink-400 uppercase">Tier</p></div>
          <div className="grid grid-cols-3 gap-3">{(['essentials','compliance_pro','advanced_governance'] as SubscriptionTier[]).map(tier => (<button key={tier} type="button" onClick={() => setBldgForm({...bldgForm, tier})} className={`p-3 rounded-xl border-2 text-left ${bldgForm.tier === tier ? 'border-accent-500 bg-accent-50' : 'border-ink-100 hover:border-ink-200'}`}><p className="font-bold text-ink-900">{TIER_LABELS[tier]}</p><p className="text-lg font-bold text-accent-600">{fmt(TIER_PRICES[tier])}<span className="text-xs font-normal text-ink-400">/mo</span></p><p className="text-xs text-ink-400 mt-1">{Object.entries(TIER_FEATURES[tier]).filter(([,v]) => v).length} features</p></button>))}</div>
        </div>
      </Modal>)}

      {modal === 'addUser' && (<Modal title="Add Platform User" onClose={() => setModal(null)} onSave={() => { if (!userForm.name || !userForm.email) { alert('Required'); return; } store.addPlatformUser({ id: `padm-${Date.now()}`, name: userForm.name, email: userForm.email, role: userForm.role, status: 'active', lastLogin: '', createdAt: new Date().toISOString().split('T')[0], buildings: ['*'] }); store.addAuditEntry({ actor: ACTOR, actorRole: 'super_admin', action: 'user.create', target: userForm.name, details: `Created (${userForm.role})`, buildingId: null }); setModal(null); }} saveLabel="Create"><div className="space-y-4"><div><label className="block text-sm font-medium text-ink-700 mb-1">Name *</label><input value={userForm.name} onChange={e => setUserForm({...userForm, name: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Email *</label><input value={userForm.email} onChange={e => setUserForm({...userForm, email: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Role</label><select value={userForm.role} onChange={e => setUserForm({...userForm, role: e.target.value as PlatformUser['role']})} className="w-full px-3 py-2 border border-ink-200 rounded-lg bg-white"><option value="super_admin">Super Admin</option><option value="support">Support</option><option value="billing">Billing</option><option value="readonly">Read Only</option></select></div></div></Modal>)}

      {modal === 'addTicket' && (<Modal title="Create Support Ticket" onClose={() => setModal(null)} onSave={() => { if (!tktForm.subject || !tktForm.buildingId) { alert('Building and subject required'); return; } const b = tenants.find(t => t.id === tktForm.buildingId); store.addTicket({ buildingId: tktForm.buildingId, buildingName: b?.name || '', subject: tktForm.subject, description: tktForm.description, status: 'open', priority: tktForm.priority, assignedTo: null, createdBy: ACTOR }); setModal(null); }} saveLabel="Create"><div className="space-y-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">Building *</label><select value={tktForm.buildingId} onChange={e => setTktForm({...tktForm, buildingId: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm"><option value="">Select...</option>{tenants.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Subject *</label><input value={tktForm.subject} onChange={e => setTktForm({...tktForm, subject: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Description</label><textarea value={tktForm.description} onChange={e => setTktForm({...tktForm, description: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm" rows={3} /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Priority</label><select value={tktForm.priority} onChange={e => setTktForm({...tktForm, priority: e.target.value as SupportTicket['priority']})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div></div></Modal>)}

      {modal === 'addAnn' && (<Modal title="New Announcement" onClose={() => setModal(null)} onSave={() => { if (!annForm.title) { alert('Title required'); return; } store.addAnnouncement({ title: annForm.title, message: annForm.message, audience: annForm.audience, status: 'draft', createdBy: ACTOR }); setModal(null); }} saveLabel="Save Draft"><div className="space-y-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">Title *</label><input value={annForm.title} onChange={e => setAnnForm({...annForm, title: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Message</label><textarea value={annForm.message} onChange={e => setAnnForm({...annForm, message: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm" rows={4} /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Audience</label><select value={annForm.audience} onChange={e => setAnnForm({...annForm, audience: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm"><option value="all">All Buildings</option><option value="essentials">Essentials Tier</option><option value="compliance_pro">Compliance Pro</option><option value="advanced_governance">Advanced Governance</option></select></div></div></Modal>)}

      {modal === 'editTemplate' && tmplEditId && (<Modal title="Edit Email Template" onClose={() => { setModal(null); setTmplEditId(null); }} onSave={() => { store.updateTemplate(tmplEditId, { subject: tmplForm.subject, body: tmplForm.body }); setModal(null); setTmplEditId(null); }} saveLabel="Save" wide><div className="space-y-3"><div><label className="block text-sm font-medium text-ink-700 mb-1">Subject Line</label><input value={tmplForm.subject} onChange={e => setTmplForm({...tmplForm, subject: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm font-mono" /></div><div><label className="block text-sm font-medium text-ink-700 mb-1">Body</label><textarea value={tmplForm.body} onChange={e => setTmplForm({...tmplForm, body: e.target.value})} className="w-full px-3 py-2 border border-ink-200 rounded-lg text-sm font-mono" rows={12} /></div><p className="text-[10px] text-ink-400">Variables: {'{{building_name}}, {{contact_name}}, {{subdomain}}, {{tier_name}}, {{trial_end_date}}, {{amount}}, {{compliance_score}}'}</p></div></Modal>)}
    </div>
  );
}

